# Generated by Django 4.2.20 on 2025-04-10 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_money_to_transfer', models.FloatField()),
                ('money_type', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('enter_destination_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_moneytransfers', to=settings.AUTH_USER_MODEL)),
                ('enter_your_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_moneytransfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_money_to_transfer', models.FloatField()),
                ('money_type', models.CharField(max_length=50)),
                ('transfer_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=12)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('enter_destination_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_moneyrequests', to=settings.AUTH_USER_MODEL)),
                ('enter_your_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_moneyrequests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=1000)),
                ('money_type', models.CharField(choices=[('GB Pounds', 'GB Pounds'), ('US dollars', 'US dollars'), ('Euros', 'Euros')], default='GB Pounds', max_length=12)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
